name: rrmm
channels:
  - conda-forge
dependencies:
  - python>3.11
  - scipy
  - matplotlib
  - numpy
  - ipykernel
  - pint
  - pandas
  - pip
   - pip:
     - git+https://github.com/rootmemo/pyrootmemo.git
  
