[tool.poetry]
name = "pyrootmemo"
version = "0.1.0"
description = "A Python package for modelling the contribution of root systems to the shear strength of soil."
authors = [
    "Anil Yildiz <yildiz@mbd.rwth-aachen.de>",
    "Gerrit J. Meijer <gjm36@bath.ac.uk>",
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/rootmemo/pyrootmemo"
repository = "https://github.com/rootmemo/pyrootmemo"
documentation = "https://pyrootmemo.readthedocs.io"
keywords = [
    "root reinforcement",
    "slope stability",
    "soil mechanics",
    "geotechnical engineering",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.12"
numpy = ">2.1"
Pint = "^0.24.4"
matplotlib = ">3.9"
pandas = ">2.2"
scipy = ">1.14"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^9.1.1"

[tool.poetry.group.docs.dependencies]
sphinx = "^8.2.3"
sphinx-autobuild = "^2024.10.3"
sphinx-rtd-theme = "^3.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
