# import packages and functions
import numpy as np
from pyrootmemo.tools.helpers import units
from pint import Quantity


# WWM class
class Wwm():
    """
    Class for Wu/Waldron Model.
           
    The class constains some additional methods:
    * 'peak_force()': calculate peak force in root bundle (sum of strenghts)
    * 'peak_reinforcement()': calculate peak root reinforcement, given a known
      soil area and Wu/Waldron orientation factor 'k'
    
    """

    # initialise class
    def __init__(
            self, 
            roots
            ) -> None:
        """
        Initiate RBMw bundle model class

        Parameters
        ----------
        roots : instance of MultipleRoots class. 
            Must contain fields 'diameter', 'xsection', 'tensile_strength'

        Returns
        -------
        None.

        """
        # set parameters
        self.roots = roots


    # Calculate peak force 
    def peak_force(
            self
            ) -> float | dict:
        """
        Calculate WWM peak force

        Sum of maximum tensile forces in all roots
        """
        # force
        force = np.sum(self.roots.xsection * self.roots.tensile_strength)
        # return
        return(force)


    # reinforcement
    def peak_reinforcement(
            self, 
            soil_area: Quantity = 1.0 * units("m^2"),
            k: float = 1.2
            ) -> float:
        """
        Calculate peak reinforcement (largest soil reinforcement at any point)
        generated by the fibre bundle

        Parameters
        ----------
        soil_area : Quantity, optional
            Soil cross-sectional area that contains the roots defined. 
            The default is 1.0 m^2.
        k : float, optional
            Wu/Waldron reinforcement orientation factor. The default is 1.2.

        Returns
        -------
        float
            peak root reinforcement.

        """
        # convert area
        if not isinstance(soil_area, Quantity):
            if isinstance(soil_area, int) or isinstance(soil_area, float):
                Warning("soil area unit not defined - assumed as m^2")
                soil_area = soil_area * units("m^2")
            else:
                TypeError("soil area must be defined as area quantity")
        # return
        return(k * self.peak_force() / soil_area)
