name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main
  # You can also add:
  # pull_request:
  #   branches: [ main ]
  # or 'workflow_dispatch:' for on-demand builds.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme
          pip install -r requirements.txt

      - name: Build docs
        run: |
          cd docs
          make html

      - name: Upload built documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html
